config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  root 'store#index', as: 'store_index'
  match '*path', to: redirect('404'), via: :all, constraints: -> (req) { req.headers['User-Agent'] =~ FIREFOX_BROWSER_REGEX }
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users 
  resources :orders
  resources :line_items
  resources :carts

  resources :products, path: '/books' do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [ :index, :update ]

  get 'my-orders', to: 'users#orders'
  get 'my-items', to: 'users#items'

  namespace :admin do
    get 'reports', to: 'reports#index'
    get 'categories', to: 'categories#index'
    get '/', to: redirect('/admin/reports')
  end

  resources :categories do
    resources :products, path: '/books', as: 'books', constraints: { category_id: CATEGORY_ID_REGEX }
    resources :products, path: '/books', as: 'books', to: redirect('/')
  end

  post 'language', to: 'users#language', as: 'user_language'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, counter_cache: true
  has_many :line_items
  # specifying indirect relationship through another entity
  has_many :orders, through: :line_items
  has_many :ratings, dependent: :destroy

  before_destroy :ensure_not_referenced_by_any_line_item

  # Adding validation related to Product text field for not being empty
  validates :title, :description, :image_url, :price, :discount_price, presence: true

  validates :discount_price,
            numericality: { greater_than: 0 },
            allow_blank: true

  # Adding validation related to price being positive number
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }, comparison: {
                      greater_than: :discount_price,
                      message: "must be greater than discount price",
                    }, allow_blank: true

  # Validation for title being unique
  validates :title, uniqueness: true

  validates :permalink, uniqueness: true, format: { with: PERMALINK_REGEX, message: "Permalink -  no special character and no space allowed" }

  validates :permalink_length_without_hyphen, comparison: { greater_than_or_equal_to: 3 }

  validates_length_of :words_in_description,
                      in: 5..10,
                      too_short: "must be more than 5",
                      too_long: "must be less than 10",
                      allow_blank: true

  validates :image_url,
            image_url: true,
            allow_blank: true

  before_validation :default_title_value
  before_validation :default_discount_value

  after_create_commit :increment_parent_category_products_count, if: :category_parent_present?
  after_destroy_commit :decrement_parent_category_products_count, if: :category_parent_present?
  scope :enabled_products, -> { where(enabled: true) }
  scope :product_ordered, -> { joins(:line_items).distinct }
  scope :ordered_titles, -> { product_ordered.pluck(:title) }

  private def words_in_description
    description.scan(DESCRIPTION_WORDS_REGEX)
  end

  private def permalink_length_without_hyphen
    permalink.split("-").length
  end

  private def default_title_value
    self.title ||= 'abc'
  end

  private def default_discount_value
    self.discount_price ||= self.price
  end

  private def increment_parent_category_products_count
    category.parent.increment!(:products_count)
  end

  private def decrement_parent_category_products_count
    category.parent.increment!(:products_count)
  end

  private def category_parent_present?
    category.present? && category.parent.present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  before_action :set_product, only: %i[ show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_product

  # GET /products or /products.json
  def index
    if params[:category_id]
      @products = Product.where(category_id: params[:category_id]).order(:title).includes(:ratings)
    else
      @products = Product.all.order(:title).includes(:ratings)
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all.pluck(:name, :id)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product #{t("flash.notice.successfull_create")}" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product #{t("flash.notice.successfull_update")}" }
        format.json { render :show, status: :ok, location: @product }

        ## Using Channel to send entire catalog every time update is made
        @products = Product.all.order(:title) # Required as this is used in store/index
        ## render_to_string renders according to same rules as render,
        # but returns the result in string instead of sending it as response body to browser
        # data sent as key-value pair
        # layout: false specifies that we only want view and not entire application layout page
        ActionCable.server.broadcast("products", {
          html: render_to_string("store/index", layout: false),
        })
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product #{t("flash.notice.successfull_destroyed")}" }
      format.json { head :no_content }
    end
  end

  # /products/1/who_bought.atom
  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        # This will look for template name who_bought.atom.builder
        format.atom
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(
      :title, :description, :image_url, :price,
      :enabled, :discount_price, :permalink, :category_id, images: [],
    )
  end

  def invalid_product
    logger.error "Attempt to access invalid product #{params[:id]}"

    redirect_to products_url, notice: "Invalid Product"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_html_to_overview(html, **truncate_args)
    truncate(strip_tags(html), truncate_args)
  end

  def generate_image_url(image)
    image.present? ? rails_blob_path(image, disposition: "attachment") : "default_product.png"
  end

  def generate_ratings
    (0..5).step(0.5).to_a
  end

  def average_rating(product)
    product.ratings.average(:rating) || 'Add Rating'
  end

  def current_product_rating_by_user(ratings,current_user)
    ratings.find { |rating| rating.user_id == current_user.id}.try(:rating) || 0
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div class="form-errors">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description, rows:10, cols: 60 %>
  </div>
  <div>
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories, include_blank: t('form.select.select_one') %>
  </div>
  <div>
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  <div>
    <%= form.label :images, 'Product Images' %>
    <%= form.file_field :images, accept: 'image/png,image/gif,image/jpg', multiple: true %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>
  <div>
    <%= form.label :discount_price %>
    <%= form.number_field :discount_price %>
  </div>
  <div>
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr id="<%= dom_id product %>" class="<%= cycle('list_line_odd', 'list_line_even') %>">
  <td class="description">
    <h1><%= product.title %></h1>
    <div>Users Ratings: <%= average_rating(product) %></div>
    <%= form_with url: ratings_path, method: :post, local: false do |form| %>
      <%= form.hidden_field :product_id, value: product.id %>
      <%= form.select :rating, generate_ratings, selected: current_product_rating_by_user(product.ratings, @logged_in_user) %>
      <%= form.submit 'Submit Rating' %>
    <% end %>
    <h3>Product Images</h3>
    <div class="image-container">
      <% if first_image %>
        <%= image_tag generate_image_url(product.images[0]), width: '250', height: '250' %>
      <% else %>
        <% product.images.each do |image| %>
          <%= image_tag generate_image_url(image), width: '250', height: '250' %>
        <% end %>
      <% end %>
    </div>
    <p>
      <%= format_html_to_overview(product.description, length: 80) %>
    </p>
  </td>
  <td class="actions">
    <ul>
      <li><%= link_to 'Show', product %></li>
      <li><%= link_to 'Edit', edit_product_path(product) %></li>
      <li>
        <%= 
          link_to('Destroy',
            product,
            method: :delete,
            data: { confirm: 'Are you sure?' })
        %>
      </li>
    </ul>
  </td>
</tr>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<%= render "form", product: @product %>
<br>
<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Products</h1>

<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New Product', new_product_path %>
      </td>
    </tr>
  </tfoot>

  <tbody>
    <%= render partial: @products, locals: { first_image: true } %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New product</h1>
<%= render "form", product: @product %>
<br>
<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: @product, locals: {first_image: false} %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>